"""removed and changed Session

Revision ID: 0d30a496ac8f
Revises: 
Create Date: 2020-04-02 19:43:26.311514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d30a496ac8f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Admin_Table',
    sa.Column('username', sa.String(length=35), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('mobile', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('mobile'),
    sa.UniqueConstraint('username')
    )
    op.create_table('Question_Table',
    sa.Column('q_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('q_id')
    )
    op.create_table('Session',
    sa.Column('s_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('domain', sa.String(length=20), nullable=True),
    sa.Column('scheduled_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('s_id')
    )
    op.create_table('Student_Info',
    sa.Column('mobile', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=70), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=150), nullable=True),
    sa.Column('city', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('mobile')
    )
    op.create_table('Feedback',
    sa.Column('f_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('areaofinterest', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('session', sa.Integer(), nullable=True),
    sa.Column('mobile', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['mobile'], ['Student_Info.mobile'], ),
    sa.ForeignKeyConstraint(['session'], ['Session.s_id'], ),
    sa.PrimaryKeyConstraint('f_id')
    )
    op.create_table('Response',
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(length=50), nullable=True),
    sa.Column('session', sa.Integer(), nullable=True),
    sa.Column('stud_mobile', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['session'], ['Session.s_id'], ),
    sa.ForeignKeyConstraint(['stud_mobile'], ['Student_Info.mobile'], ),
    sa.PrimaryKeyConstraint('response_id')
    )
    op.create_table('Session_Stud',
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('stud_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['Session.s_id'], ),
    sa.ForeignKeyConstraint(['stud_id'], ['Student_Info.mobile'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Session_Stud')
    op.drop_table('Response')
    op.drop_table('Feedback')
    op.drop_table('Student_Info')
    op.drop_table('Session')
    op.drop_table('Question_Table')
    op.drop_table('Admin_Table')
    # ### end Alembic commands ###
