"""increased data size for description

Revision ID: 5336fc938c1c
Revises: a0166b1bdb6a
Create Date: 2020-04-25 20:33:24.202068

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5336fc938c1c'
down_revision = 'a0166b1bdb6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Feedback', 'description',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=1300),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Feedback', 'description',
               existing_type=sa.String(length=1300),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=False)
    # ### end Alembic commands ###
