"""changed Feedback type to datetime

Revision ID: 702008fc2df1
Revises: 324ee6ff40ec
Create Date: 2020-04-02 17:03:32.868203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '702008fc2df1'
down_revision = '324ee6ff40ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Session', 'scheduled_on',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Session', 'scheduled_on',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    # ### end Alembic commands ###
