"""added cascade delete

Revision ID: a0916681e0d6
Revises: bf15b6e4f127
Create Date: 2020-05-31 10:10:23.254765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0916681e0d6'
down_revision = 'bf15b6e4f127'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Question_Table_ibfk_1', 'Question_Table', type_='foreignkey')
    op.create_foreign_key(None, 'Question_Table', 'Session', ['session_id'], ['s_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Question_Table', type_='foreignkey')
    op.create_foreign_key('Question_Table_ibfk_1', 'Question_Table', 'Session', ['session_id'], ['s_id'])
    # ### end Alembic commands ###
