"""added questions

Revision ID: bf15b6e4f127
Revises: 59119c063adf
Create Date: 2020-05-23 15:07:23.467348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf15b6e4f127'
down_revision = '59119c063adf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Session', sa.Column('cert', sa.String(length=150), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Session', 'cert')
    # ### end Alembic commands ###
