"""added sentiment to feedback

Revision ID: cdc820cc2c86
Revises: 0d30a496ac8f
Create Date: 2020-04-03 13:53:39.532144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdc820cc2c86'
down_revision = '0d30a496ac8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Feedback', sa.Column('sentiment', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Feedback', 'sentiment')
    # ### end Alembic commands ###
